"""MercSoft API backend tests."""
import os
import time
import pytest
import requests
from pymongo import MongoClient

BASE_URL = os.environ.get("REACT_APP_BACKEND_URL", "http://localhost:3000").rstrip("/")
API = f"{BASE_URL}/api"

MONGO_URL = os.environ.get("MONGO_URL", "mongodb://localhost:27017")
DB_NAME = os.environ.get("DB_NAME", "test_database")


@pytest.fixture(scope="module")
def db():
    cli = MongoClient(MONGO_URL)
    return cli[DB_NAME]


# ========== /api/ root ==========
def test_root_status():
    r = requests.get(f"{API}/", timeout=15)
    assert r.status_code == 200
    data = r.json()
    assert data.get("status") == "ok"
    assert "MercSoft" in data.get("message", "")


# ========== /api/config ==========
def test_config_returns_phone_and_email():
    r = requests.get(f"{API}/config", timeout=15)
    assert r.status_code == 200
    data = r.json()
    assert data.get("contact_phone") == "2221401900"
    assert data.get("contact_email") == "lalogalindo@gmail.com"


# ========== /api/contact validation errors ==========
def test_contact_missing_required_fields_returns_422():
    r = requests.post(f"{API}/contact", json={"name": "x"}, timeout=15)
    assert r.status_code == 422


def test_contact_invalid_email_returns_422():
    r = requests.post(
        f"{API}/contact",
        json={
            "name": "Test User",
            "email": "not-an-email",
            "subject": "Hello",
            "message": "Hi",
            "recaptcha_token": "any-token",
        },
        timeout=15,
    )
    assert r.status_code == 422


def test_contact_empty_recaptcha_token_returns_422():
    """min_length=1 on recaptcha_token => empty string is 422 (Pydantic)."""
    r = requests.post(
        f"{API}/contact",
        json={
            "name": "Test User",
            "email": "test@example.com",
            "subject": "Hello",
            "message": "Hi there",
            "recaptcha_token": "",
        },
        timeout=15,
    )
    assert r.status_code == 422


# ========== /api/contact happy path ==========
# NOTE: Google's test secret only accepts tokens minted by the test site-key in
# a real browser (it returns invalid-input-response for arbitrary strings).
# So the full success path cannot be verified with pure HTTP. The UI test
# (Playwright) covers it. We additionally assert here that the backend rejects
# bogus tokens with HTTP 400 (reCAPTCHA verification failed) -- this validates
# the verify_recaptcha → 400 branch.
def test_contact_bogus_recaptcha_returns_400(db):
    payload = {
        "name": "TEST_Backend Tester",
        "email": "TEST_tester@example.com",
        "company": "TEST_Co",
        "subject": "TEST_Automated backend test",
        "message": "TEST_This submission was generated by automated tests.",
        "recaptcha_token": "bogus-token-not-from-real-widget",
        "locale": "en",
    }
    r = requests.post(f"{API}/contact", json=payload, timeout=45)
    assert r.status_code == 400
    assert "reCAPTCHA" in r.text or "recaptcha" in r.text.lower()


# ========== Cleanup ==========
@pytest.fixture(scope="module", autouse=True)
def cleanup_test_data(db):
    yield
    db.contact_submissions.delete_many({"name": {"$regex": "^TEST_"}})
